-- MySQL Script generated by MySQL Workbench
-- Mon Sep 16 20:24:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_epis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_epis` ;

-- -----------------------------------------------------
-- Schema db_epis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_epis` DEFAULT CHARACTER SET utf8 ;
USE `db_epis` ;

-- -----------------------------------------------------
-- Table `db_epis`.`colaboradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_epis`.`colaboradores` ;

CREATE TABLE IF NOT EXISTS `db_epis`.`colaboradores` (
  `id_colaborador` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `matricula` VARCHAR(255) NULL DEFAULT NULL,
  `departamento` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_colaborador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_epis`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_epis`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `db_epis`.`usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `usuario` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `tipo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_epis`.`emprestimos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_epis`.`emprestimos` ;

CREATE TABLE IF NOT EXISTS `db_epis`.`emprestimos` (
  `id_emprestimo` INT(11) NOT NULL AUTO_INCREMENT,
  `id_colaborador` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `data_emprestimo` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_devolucao` TIMESTAMP NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_emprestimo`),
  INDEX `id_colaborador_idx` (`id_colaborador` ASC),
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_colaborador_emprestimo`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `db_epis`.`colaboradores` (`id_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_emprestimo`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_epis`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_epis`.`equipamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_epis`.`equipamentos` ;

CREATE TABLE IF NOT EXISTS `db_epis`.`equipamentos` (
  `id_equipamento` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `quantidade_total` INT(11) NULL DEFAULT NULL,
  `quantidade_disponivel` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_equipamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_epis`.`emprestimo_equipamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_epis`.`emprestimo_equipamentos` ;

CREATE TABLE IF NOT EXISTS `db_epis`.`emprestimo_equipamentos` (
  `id_emprestimo_equipamento` INT(11) NOT NULL AUTO_INCREMENT,
  `id_emprestimo` INT(11) NOT NULL,
  `id_equipamento` INT(11) NOT NULL,
  PRIMARY KEY (`id_emprestimo_equipamento`),
  INDEX `idx_emprestimo` (`id_emprestimo` ASC),
  INDEX `idx_equipamento` (`id_equipamento` ASC),
  CONSTRAINT `fk_emprestimo_equipamentos_emprestimos`
    FOREIGN KEY (`id_emprestimo`)
    REFERENCES `db_epis`.`emprestimos` (`id_emprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_equipamentos_equipamentos`
    FOREIGN KEY (`id_equipamento`)
    REFERENCES `db_epis`.`equipamentos` (`id_equipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_epis`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_epis`.`logs` ;

CREATE TABLE IF NOT EXISTS `db_epis`.`logs` (
  `id_log` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `acao` VARCHAR(255) NULL DEFAULT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_log`),
  INDEX `id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_logs_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_epis`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;